### ISSUE TITLE
add test methods for adds, query, update, delete

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet-firestore#17]
## Details of Improvement
- I want to adds test method (Add, Query, Update, Delete).

## Reference Issue
#9 

## Expected behavior
implements tests below

- [x] Adds Collection Items
- [x] Get Collection Item
- [x] Query Collection Items
- [x] Update Collection Item
- [x] Delete Collection Item

**Comment by euledge** [comment]
ミスっていたところ
- idの重複登録
- awaitの漏れ

ですね。review&fix ありがとうございます。

**Comment by KishiTheMechanic** [comment]
はい、そんな感じでした！
あとはissueも上げていただいたところなんですが今のところfirestoreのqueryに制限があるようでした！(レンジ使うと2種類以上のfieldで並び替えできない)

こちらこそいつもありがとうございます！

引き続きよろしくお願いいたします🙌
