### ISSUE TITLE
need client Api with Firestore Security Rule

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet-firestore#19]
クライアント側からアクセス可能なプラグインがあると嬉しい

## Details of Improvement
このプラグインは、Admin SDKを用いて実装されているため FirestoreのSecurty Ruleを無視してアクセスすることが可能になっています。

バックエンドで行う想定のプラグインだとは思いますが、クライアント APIを使用すれば、クライアントからSecurity Ruleで制御された安全なアクセスが可能になります。

Reference, Snapshotをチェーンして必要なデータを取得するのはAdmin SDKと同じように煩雑な操作があり毎回書くのは面倒と感じます。

## Expected behavior
- 現在のインタフェースと同様な（Firestore Converter、型安全）クライアントAPIを用いてSecurity Ruleによって制御されているプラグインが提供されると嬉しい

## Reference

https://firebase.google.com/docs/reference/js/firestore_?hl=ja

**Comment by KishiTheMechanic** [comment]
フロントエンドからは、'firebase/firestore'をそのまま使って、コンバーターを差し込んでいますが、これもプラグインに入れたほうが使いやすいでしょうか？

このプラグインはサーバーサイド用としていて、フロントエンドを外していた理由としては、メソッド名が競合しそうだったからです。

adminの方は複雑なのでラッパーが欲しかったのですが、
v9のクライアントからの取得は例えばこのようになっていて、
https://github.com/elsoul/skeet-next/blob/main/src/components/pages/user/chat/ChatBox.tsx#L110C5-L115C43
(このcreateFirestoreDataConverterはsrc/libからのimportなことに気をつけてください)

特別にラッパーを用意しなくても既に使いやすい形だと思っています。

このあたりご意見いただければ嬉しいです🙌

いつもありがとうございます！
引き続きよろしくお願いいたします。

**Comment by KishiTheMechanic** [comment]
withConverterを毎回つけるのはたしかに少し面倒なので、このあたりは改善できそうです。
その場合、プラグインはフロントエンド用と分けたほうが良いかもしれません。
そうすると、サーバーサイドと同じようにadd<Type>というAPIを提供できます。
例えば、'@skeet-framework/firestore-client'
のようなパッケージになるかと思います！

**Comment by euledge** [comment]
検討ありがとうございます。まず少し現在の実装のまま、もう少し使ってみて書き心地を試して、不便そうなところあるか試してみます。

**Comment by KishiTheMechanic** [comment]
これやってみたんですが、(import { add } from '@skeet-framework/firestore/client' のようにして)
どうやらimportしたnpmパッケージにFirestoreのdbを突っ込むと動作しなくなるみたいです！
同じヘルパー関数をReact内に作って使うと使えます。

なので、作ったヘルパー関数はフロントエンドのlibに突っ込んで使えるようにしておきます！
後ほどテンプレートの方更新しますので、そちらの使い心地を試していただきたいです！

引き続きよろしくお願いいたします！

**Comment by KishiTheMechanic** [comment]
https://github.com/elsoul/skeet-next/tree/main/src/lib/skeet/firestore/lib

Next.js + Firestoreのテンプレートに、Firestoreのフロントエンド用ヘルパー関数を追加してみました！

使い方は
https://github.com/elsoul/skeet-next/blob/main/src/layouts/user/UserLayout.tsx

このように使えるので、より簡単に取り扱うことができるようになりました🙌

**Comment by euledge** [comment]
こちら、対応いただいたもので使えそうなのでクローズします。
いつも対応いただきありがとうございます👍

**Comment by KishiTheMechanic** [comment]
ご確認ありがとうございます！

こちらこそいつもありがとうございます🙌
