### ISSUE TITLE
Incorrect usage example of advancedConditions

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet-firestore#21]
READMEにある advancedConditionsの条件で ageとnameの複合条件の例示がありますが
テストの中のコメントと一致していないと思います。

## README
https://github.com/elsoul/skeet-firestore/blob/fdc8338f55b40afdc27245419990f834ec3666cb/README.md?plain=1#L160

## テスト内のコメント
https://github.com/elsoul/skeet-firestore/blob/fdc8338f55b40afdc27245419990f834ec3666cb/tests/firestore_spec.test.ts#L194

**Comment by KishiTheMechanic** [comment]
ご指摘ありがとうございます！
readme修正します！
