### ISSUE TITLE
[Question] document html write one line is code format rule in this project

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet-firestore#39]
以下のように、documentのhtmlで改行なしに1行で書いているのは意図してのことでしょうか?

![image](https://github.com/elsoul/skeet-firestore/assets/1209580/c4310d48-797b-4efd-aafa-635b26cfd223)

今のprettierの設定だと、強制的に改行してしまうので、この書き方を保つのならばformatさせないように .prettierignore に含めたほうが良いと思います。

- yarn format だと.prettierignoreにないのでhtmlもフォーマットされてしまう。  
``` 
.next
out
dist
build
src/__generated__
src/schema.graphql
```
- lint-stagedによるコミット時のhookにはhtmlは含まれないのでフォーマットされない。  

``` json
  "lint-staged": {
    "*.{ts,css,md}": "prettier --write"
  }
```

**Comment by KishiTheMechanic** [comment]
ありがとうございます！
.prettierignoreに追加しました👍
